version: "3.0"
services:
  backend:
    image: thingspanel/thingspanel-go:latest
    ports:
      - "9999:9999"
      - "9998:9998"
    networks:
      extnetwork:
        ipv4_address: 172.19.0.2
    links:
      - database
      - gmqtt
    volumes:
      - ./init_files/backend/:/go/src/
    ulimits:
      nproc: 524288
      nofile:
        soft: 20000
        hard: 40000

  frontend:
    image: thingspanel/thingspanel-vue:latest
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - backend
    hostname: frontend
    networks:
      extnetwork:
        ipv4_address: 172.19.0.3
    links:
      - backend
    volumes:
      - ./init_files/html:/usr/share/nginx/html/
      - ./init_files/nginx.conf:/etc/nginx/nginx.conf

  database:
    image: timescale/timescaledb:latest-pg12
    user: postgres
    volumes:
      - ./init_files/backend/TP.sql:/docker-entrypoint-initdb.d/TP.sql
    ports:
      - "5432:5432"
    environment:
      - "TZ=Asia/Shanghai"
      - "LC_ALL=C.UTF-8"
      - "POSTGRES_DB=ThingsPanel"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgresThingsPanel2022"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    hostname: postgres
    networks:
      extnetwork:
        ipv4_address: 172.19.0.4

  gmqtt:
    image: thingspanel/thingspanel-gmqtt:latest
    ports:
      - "1883:1883"
    hostname: gmqtt
    networks:
      extnetwork:
        ipv4_address: 172.19.0.5

networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/16
#          gateway: 172.19.0.1



