version: "3.8"
services:
  backend:
    restart: always
    build:
      context: ../ThingsPanel-Go
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    hostname: backend
    links:
      - gmqtt
      - database

  frontend:
    build:
      context: ../ThingsPanel-Backend-Vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    hostname: frontend
    links:
      - backend

  database:
    image: timescale/timescaledb:latest-pg14
    user: postgres
    volumes:
      - ./init_files/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./init_files/TP.sql:/docker-entrypoint-initdb.d/TP.sql
    ports:
      - "5432:5432"
    environment:
      - "LC_ALL=C.UTF-8"
      - "POSTGRES_DB=ThingsPanel"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_HOST=host.docker.internal"
      - "POSTGRES_PASSWORD=postgres"
    hostname: postgres

  gmqtt:
    build:
      context: ../Gmqtt
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
