version: "3.0"
services:
  frontend:
    image: thingspanel/thingspanel-vue:v0.3.0
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - backend
    hostname: frontend
    networks:
      extnetwork:
        ipv4_address: 172.19.0.3
    links:
      - backend
    volumes:
      - thingspanel-html:/usr/share/nginx/html
      - ./init_files/nginx.conf:/etc/nginx/nginx.conf

  database:
    image: timescale/timescaledb:latest-pg12
    user: postgres
    volumes:
      - ./init_files/sql/TP.sql:/docker-entrypoint-initdb.d/TP.sql
      - thingspanel-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "TZ=Asia/Shanghai"
      - "LC_ALL=C.UTF-8"
      - "POSTGRES_DB=ThingsPanel"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgresThingsPanel2022"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    hostname: postgres
    networks:
      extnetwork:
        ipv4_address: 172.19.0.4

  gmqtt:
    image: thingspanel/thingspanel-gmqtt:v0.3.0
    ports:
      - "1883:1883"
    hostname: gmqtt
    networks:
      extnetwork:
        ipv4_address: 172.19.0.5

  redis:
    image: redis:6.2.7
    command: redis-server --requirepass redis2022
    volumes:
      - ./init_files/redis/data:/data
      - ./init_files/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./init_files/redis/logs:/logs
    ports:
      - "6379:6379"
    hostname: redis
    networks:
      extnetwork:
        ipv4_address: 172.19.0.6

  backend:
    command: sh -c './wait-for-postgres.sh 172.19.0.4 postgres'
    image: thingspanel/thingspanel-go:v0.3.0
    ports:
      - "9999:9999"
      - "9998:9998"
    networks:
      extnetwork:
        ipv4_address: 172.19.0.2
    depends_on:
      - gmqtt
      - database
      - redis
    links:
      - database
      - gmqtt
      - redis
    volumes:
      - ./init_files/backend/logs:/app/files/logs
      - thingspanel-go:/app
    ulimits:
      nproc: 524288
      nofile:
        soft: 20000
        hard: 40000
volumes:
  thingspanel-go: {}
  thingspanel-html: {}
  thingspanel-postgres: {}

networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/16



