pm25:
  type: 'app'
  name: '空气质量监测'
  device: '空气质量监测v1.0'
  description: ''
  version: '1.0.0'
  author: '字段【PM2.5值，PM10值，PM100值】'
  email: ''
  widgets:
    air_quality_index:
      name: '空气污染指数'
      description: '空气污染指数'
      receiver: ''
      template: 'air-quality-index'
      fields:
        pm25:
          name: 'PM2.5'
          type: 2
          symbol: 'ug/m3'
    pm25_value:
      name: 'PM2.5值'
      description: 'PM2.5信息'
      receiver: 'Pm25'
      thumbnail: '/pm25.png'
      template: 'pm25-value'
      fields:
        pm25:
          name: 'PM2.5'
          type: 3
          symbol: 'ug/m3'
    pm10_value:
      name: 'PM10值'
      description: 'PM10信息'
      receiver: 'Pm10'
      thumbnail: '/pm25.png'
      template: 'pm10-value'
      fields:
        pm10:
          name: 'PM10'
          type: 3
          symbol: 'ug/m3'
    pm100_value:
      name: 'PM100值'
      description: 'PM100信息'
      receiver: 'Pm100'
      thumbnail: '/pm25.png'
      template: 'pm100-value'
      fields:
        pm100:
          name: 'PM100'
          type: 3
          symbol: 'ug/m3'
    pm25_line:
      name: 'PM2.5曲线'
      description: 'PM2.5信息'
      receiver: 'Pm25'
      thumbnail: '/pm25.png'
      template: 'pm25-line'
      fields:
        pm25:
          name: 'PM2.5'
          type: 3
          symbol: 'ug/m3'
    pm10_line:
      name: 'PM10曲线'
      description: 'PM10信息'
      receiver: 'Pm10'
      thumbnail: '/pm25.png'
      template: 'pm10-line'
      fields:
        pm10:
          name: 'PM10'
          type: 3
          symbol: 'ug/m3'
    doubleline_chart:
      name: 'PM25PM10双曲线'
      description: 'PM25PM10双曲线'
      receiver: ''
      thumbnail: '/pm25.png'
      template: 'doubleline-chart'
      fields:
        pm25:
          name: 'PM2.5'
          type: 3
          symbol: 'ug/m3'
        pm10:
          name: 'PM10'
          type: 3
          symbol: 'ug/m3'